name: otoh_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - kuzu-python
  - jupyter
  - matplotlib
  - ipykernel
  - openai
  - tiktoken
  - sentence-transformers
  - pytorch
  - pip:
      - tqdm
      - pyyaml
      - langchain
      - llama-index
