name: llm-comparison-multi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - networkx
  - pydantic>=2.0
  - scikit-learn
  - tqdm
  - python-dotenv
  - plotly
  - streamlit
  - pip
  - pip:
    # Core dependencies para o projeto
    - openai>=1.0.0
    - loguru
    
    # Graph database (Kùzu)
    - kuzu>=0.4.0
    
    # Embedding e busca vetorial - versões compatíveis
    - sentence-transformers>=2.2.0
    - faiss-cpu
    
    # Fix compatibility issues
    - pyarrow>=12.0.0
    - datasets>=2.14.0
    
    # Avaliação
    - rouge-score
    - bert-score
    
    # Development e testing
    - pytest
    - pytest-cov
    - black
    - flake8
    
    # Performance monitoring
    - psutil