name: otoh-llm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - networkx
  - pydantic>=2.0
  - scikit-learn
  - sentence-transformers
  - transformers
  - pytorch
  - tqdm
  - python-dotenv
  - jupyter
  - ipykernel
  - pip
  - pip:
    - langchain
    - openai
    - llama-index
    - loguru
    - pyyaml