name: llm-comparison-multi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - networkx
  - pydantic>=2.0
  - scikit-learn
  - sentence-transformers
  - transformers
  - pytorch
  - tqdm
  - python-dotenv
  - jupyter
  - ipykernel
  - plotly
  - streamlit
  - pip
  - pip:
    # Core LLM and RAG libraries
    - langchain>=0.1.0
    - openai>=1.0.0
    - llama-index>=0.9.0
    
    # Logging and utilities
    - loguru
    - pyyaml
    
    # Graph database
    - kuzu>=0.4.0
    
    # Enhanced embeddings and ML
    - faiss-cpu
    - chromadb
    
    # Data processing
    - datasets
    - beautifulsoup4
    - requests
    
    # Evaluation and metrics
    - rouge-score
    - bert-score
    - evaluate
    
    # Development and testing
    - pytest
    - pytest-cov
    - black
    - flake8
    - mypy
    
    # Visualization and dashboard
    - streamlit-option-menu
    - altair
    - seaborn
    
    # Performance monitoring
    - psutil
    - memory-profiler